@startuml

autonumber
header: Core
title: Contract Management

box "Peer A"
  participant "Manager" as m1
end box
box "Directory"
  participant "Directory" as directory
end box
box "Peer B"
  participant "Manager" as m2
end box

m1 -> directory: Get Manager address of Peer B
return Manager address of Peer B
m1 -> m2 ++ : Contract proposal (signed by initiating Peer)

return Valid Contract (signed by all Peers)

skinparam sequenceBoxBorderColor #transparent
skinparam boxPadding 50
hide footbox
@enduml
