@startuml
title mTLS connections with Trust Anchor X.509 certificates

frame "Group" {
  frame "Consuming Peer" {
    component Outway as outway
    component "Contract Manager" as contractManagerConsumingPeer
  }
  frame "Providing Peer" {
     Component Inway as inway
     component "Contract Manager" as contractManagerProvidingPeer
  }
  component Directory as directory
}

contractManagerConsumingPeer <-[bold,#green]l-> contractManagerProvidingPeer
contractManagerProvidingPeer -[bold,#green]d-> directory
contractManagerConsumingPeer -[bold,#green]d-> directory
outway -[bold,#green]d-> directory
outway -[bold,#green]l-> inway
outway -[hidden]u-> contractManagerConsumingPeer
inway -[hidden]u-> contractManagerProvidingPeer

skinparam boxPadding 50
skinparam linetype polyline
skinparam linetype ortho
@enduml
