@startuml

header: Core
title: Register and discover a Service

box "Providing Peer"
  participant "Inway" as inway
end box
box "Group"
  participant "Directory" as directory
end box
box "Consuming Peer"
  participant "Outway" as outway
end box
inway -> directory ++ : register Service
return
outway -> directory ++ : discover Service
return

skinparam sequenceBoxBorderColor #transparent
skinparam boxPadding 50
hide footbox
@enduml
