@startuml
title: Register and discover a service

box "Providing Peer"
  participant "Inway" as inway
end box
box "Group"
  participant "Directory" as directory
end box
box "Requesting Peer"
  participant "Outway" as outway
end box
inway -> directory ++ : register service
return
outway -> directory ++ : discover service
return

skinparam sequenceBoxBorderColor #transparent
skinparam boxPadding 50
hide footbox
@enduml