@startuml
title: Connecting to a Service

box "Consuming Peer"
  participant "Contract Manager" as contractManagerPeer
end box

box "Providing Peer"
  participant "Contract Manager" as contractManagerDirectory
end box

contractManagerPeer -> contractManagerPeer: Create Contract with a Connection Grant
contractManagerPeer -> contractManagerPeer: Sign Contract
contractManagerPeer -> contractManagerDirectory: Submit Contract
contractManagerDirectory -> contractManagerPeer: Accept Contract

skinparam sequenceBoxBorderColor #transparent
skinparam boxPadding 50
hide footbox
@enduml
