@startuml
title: Basic request flow

box "Requesting Peer"
  participant "Client" as client
  participant "Outway" as outway
end box
box "Providing Peer"
  participant "Inway" as inway
  participant "Service" as service
end box
client -> outway ++
outway -> inway ++
inway -> service ++
service --> inway --
inway --> outway --
outway --> client --

skinparam sequenceBoxBorderColor #transparent
skinparam boxPadding 50
hide footbox
@enduml
