@startuml

autonumber
header: Core
title: Connecting to a Service

box "Consuming Peer"
  participant "Contract Manager" as contractManagerConsumingPeer
end box

box "Providing Peer"
  participant "Contract Manager" as contractManagerProvidingPeer
end box

contractManagerConsumingPeer -> contractManagerConsumingPeer: Create Contract with a __ServiceConnectionGrant__
contractManagerConsumingPeer -> contractManagerConsumingPeer: Add accept signature
contractManagerConsumingPeer -> contractManagerProvidingPeer: Submit Contract
contractManagerProvidingPeer -> contractManagerProvidingPeer: Add accept signature
contractManagerProvidingPeer -> contractManagerConsumingPeer: Accept Contract

skinparam sequenceBoxBorderColor #transparent
skinparam boxPadding 50
hide footbox
@enduml
